on: push

jobs:
  build:
    name: Build
    runs-on: ubuntu-20.04
    
    steps:
      - uses: actions/checkout@v2
      
      - name: Check codestyle app
        run: git ls-files src/*.{c,h} | xargs clang-format -i --verbose && git diff --exit-code

      - name: Check codestyle test
        run: git ls-files test/*.{c,h} | xargs clang-format -i --verbose && git diff --exit-code

      - name: Build test
        run: make test

      - name: Run test
        run: ./bin/test
        
      - name: Build application
        run: make
